/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.platform.commons.annotation.Testable;

class AppTest {
    @Testable void appHasAGreeting() {
        Main classUnderTest = new Main();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
